ALTER TABLE Users
DROP CONSTRAINT PK_Users_Id_Name

ALTER TABLE Users
ADD CONSTRAINT PK_Users_Id
PRIMARY KEY (Id)

ALTER TABLE Users 
ADD CONSTRAINT CHK_Username_Lenght
CHECK (DATALENGTH([Username]) >= 3)