CREATE DATABASE SoftUni

CREATE TABLE Towns(
Id INT IDENTITY(1, 1),
[Name] NVARCHAR(30) NOT NULL
)

ALTER TABLE Towns
ADD CONSTRAINT PK_Towns_Id
PRIMARY KEY (Id)


CREATE TABLE Addresses(
Id INT IDENTITY(1, 1),
AddressText NVARCHAR(MAX) NOT NULL,
TownId INT NOT NULL
)

ALTER TABLE Addresses
ADD CONSTRAINT PK_Addresses_Id
PRIMARY KEY (Id)

ALTER TABLE Addresses
ADD CONSTRAINT FK_TownId
FOREIGN KEY (TownId) REFERENCES Towns(Id);

CREATE TABLE Departments(
Id INT IDENTITY(1, 1),
[Name] NVARCHAR(30) NOT NULL
)

ALTER TABLE Departments
ADD CONSTRAINT PK_Departments_Id
PRIMARY KEY (Id)

CREATE TABLE Employees(
Id INT IDENTITY(1, 1),
FirstName NVARCHAR(18) NOT NULL,
MiddleName NVARCHAR(18),
LastName NVARCHAR(18) NOT NULL,
JobTitle NVARCHAR(30) NOT NULL,
DepartmentId INT NOT NULL,
HireDate DATE,
Salary DECIMAL(15, 2),
AddressId INT NOT NULL
)

ALTER TABLE Employees
ADD CONSTRAINT PK_Employees_Id
PRIMARY KEY (Id)

ALTER TABLE Employees
ADD CONSTRAINT FK_DepartmentId
FOREIGN KEY (DepartmentId) REFERENCES Departments(Id);

ALTER TABLE Employees
ADD CONSTRAINT FK_AddressId
FOREIGN KEY (AddressId) REFERENCES Addresses(Id);
